### ISSUE TITLE
Image URLs with identifiers buried in the path don't get unique filesnames

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#119]
See, for example,

http://images.ala.org.au/image/details?imageId=f7a14b25-6995-4f7f-b4d3-7655febbac28

The original URL is

http://static.inaturalist.org/photos/3083408/original.JPG?1456790200

This is translated into a filename ID of `dr1411||3c0c643e-37dd-4e96-9ca1-eb0b1c0abc68||original.JPG`

It looks like the ultimate cause of this is MediaStore.extractFileName which seems to do a number of transformations to get an original file name. One of the things that happens is that the last part of the path is used as the original file name.

This is a tricky problem, because changing the code here will cause the image server to re-load duplicate images, since the filename ID is what is used by the image server to decide whether it has already loaded a file.

There's a lot of code to ensure that we don't use the full URL or path. Presumably, there's a reason for that. Does anyone know what it is?

**Comment by djtfmartin** [comment]
I believe this is fixed now as image uploading uses the full URL as the identifier

**Comment by charvolant** [comment]
Tested during tests for #350

**Comment by nickdos** [comment]
Needs testing on existing records "ingest-all" style.
