### ISSUE TITLE
Replicate Cassandra across multiple servers for redundancy

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#133]
Cassandra has inbuilt capabilities for replication across multiple servers (across both "racks" and "datacentres").

If there was native redundancy, it would reduce any issues related to both large downloads from cassandra that may interrupt other users and issues related to attempting to ensure that a single cassandra host does not fail.

**Comment by djtfmartin** [comment]
Ive done this with Cassandra 3 with localised processing and indexing. See the cassandra3 branch.

**Comment by ansell** [comment]
Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/35

**Comment by djtfmartin** [comment]
closing as this is done with 2.x
