### ISSUE TITLE
Investigate relocating biocache-store/Jenkins to dedicated server

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#171]
The Jenkins instance that manages/serialises the job queue for updates using the biocache-store code is currently colocated with Cassandra on a single 8 core server. While Cassandra is not being updated it uses less than 5% of its CPU allocations. However, while updates are occurring, the full CPU allocation is being used by the combination of biocache-store and Cassandra (load averages from 18-20 are common, where 8 would indicate full utilisation without large performance impacts).

It would be useful to investigate the performance impact of relocating the Jenkins instance used to run biocache-store binaries to a dedicated instance (in the same datacentre) so Cassandra could then utilise dedicated resources for its query/update/compaction tasks.

The overall goal is to improve the performance of the resample/reprocess/reindex data load steps which are run using Jenkins, particularly in relation to future trait data.

If there is a temporary performance decrease due to network overhead, we may also need to investigate the way batches are handled to reduce the network overhead percentage.

**Comment by ansell** [comment]
In relation to the disk IO currently being used while reprocessing is occurring, iotop reports between 20 and 40MB/s of disk read, and a similar amount of disk write occurring. If Jenkins and Cassandra were located in the same data centre, they could rely on a single 1Gbps ethernet link to provide up to 125MB/s in full-duplex mode to provide for data movement of that magnitude assuming overheads could be minimised using appropriate batch sizes. 

Some of the 40MB/s are also occupied by Cassandra optimising the disk storage using compaction tasks. The data from those tasks would not be transferred across the network so would not need to be allowed for in network capacity computations.

**Comment by ansell** [comment]
Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/34

**Comment by djtfmartin** [comment]
assume this is closed or shelved (with the new cluster work).

**Comment by ansell** [comment]
It is fixed by the ``bstore-[1-4]`` nodes and the ``aws-scjenkins`` node.
