### ISSUE TITLE
Some threads take a lot longer in range processing

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#176]
The multi-threaded fixed key range processing/indexing pattern has a design flaw, in that it doesn't take into account that the keys are ordered and the ordering does not spread out large or complex records. Instead, it isolates them to a thread and its immediate neighbours. This results in the bulk processing on some threads finishing a lot earlier than others.

For example, the termination times for the current processing had only two of the eight threads alive since 3:57, and only three of the eight threads alive since 2:48. The second last thread completed at 6:44, while the last thread, which is particularly slowed by issue #173 , is still running as at 8:00. This is unnecessarily increasing the time for a total reprocess, which is required whenever new layers or other third-party attributes are added, by many hours, as there are unused CPU resources while only a single thread is processing.

**Comment by ansell** [comment]
Based on Dave's talk, one improvement for this is to upgrade to Solr-5/etc. and use hash based token range selections to distribute work, as the complex records will not necessarily be localised to a single biocache-store instance.

Another improvement is to distribute outstanding token ranges on demand when processing nodes have spare capacity, rather than assigning all of the token ranges for a given node to it before it starts.

**Comment by djtfmartin** [comment]
im going to close this, as the work is on 2.x
