### ISSUE TITLE
Upgrade to Scala-2.12 or 2.13

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#181]
biocache-store currently depends on scala-2.10, which received its final update in 2015. Scala-2.11 also [stopped receiving updates](https://github.com/scala/scala/releases/tag/v2.11.11) in 2017. The upgrade path is either Scala-2.12, or depending on timelines, Scala-2.13 when it is released.

**Comment by ansell** [comment]
One obstacle relates to the standardisation on using Akka rather than scala-actors for 2.12: http://docs.scala-lang.org/overviews/core/actors-migration-guide.html

**Comment by ansell** [comment]
Compatibility matrix for Scala and JVM's is at https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
