### ISSUE TITLE
Assertions not linked after reloading records

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#184]
I have been working on a dataset that has had issues with records in the ALA that didn't appear in their dataset anymore and records in their dataset that did not appear in the ALA. After debugging and finding the keys of records in the ALA to be out of sync with keys in the source files, I deleted the records and reloaded from the latest copies of the source data.

However, the provider of the dataset is now not able to find user assertions that were previously present.

A related symptom while loading was the occurrence of NullPointerExceptions in stacktraces which referenced assertions, tracked in #174 . I am not familiar with assertions, but is it possible to relink these assertions, or have they actually been deleted?

**Comment by djtfmartin** [comment]
@ansell  can i close this ?

**Comment by ansell** [comment]
It is possibly fixed by the new uuid-rowKey column family but I haven't tested that. Do you know whether the assertions are deleted by the ``delete-records`` command or whether they are persisted and will still be discoverable because the uuid-rowKey association will be persisted?

**Comment by djtfmartin** [comment]
the latter.
