### ISSUE TITLE
Indexed values on facet "Outlier layer count" include unknowns

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-store#185]
An examination of the values of the facet/indexed variable "Outlier layer count" in the Spatial Portal should be 0,1,2,3,4 or 5 but include the impossible values 6,7,8 and 10
![capture1](https://cloud.githubusercontent.com/assets/6656350/22574882/f6a1135e-ea05-11e6-89cf-13e6244d5916.jpg)

**Comment by djtfmartin** [comment]
this is fixed.

https://biocache.ala.org.au/ws/occurrences/search?pageSize=0&facets=outlier_layer_count
