### ISSUE TITLE
Unable to load habitat term; overwritten during processing

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#19]
I have a collection of fungi records to upload. Part of the supplied data includes a DwC habitat term. However, when uploaded to the sandbox, this term is overwritten by Terrestrial/Marine.

For example, see http://sandbox.ala.org.au/ala-hub/occurrences/cc9cc8e3-8e68-453d-941e-c4dc78a6d8f2 where "Wet sclerophyll forest" becomes "Terrestrial" 

The original source CSV is

basisOfRecord,catalogNumber,occurrenceRemarks,recordedBy,associatedTaxa,eventDate,verbatimEventDate,habitat,stateProvince,locality,verbatimLocality,verbatimLatitude,verbatimLongitude,verbatimSRS,decimalLatitude,decimalLongitude,geodeticDatum,coordinateUncertaintyInMeters,scientificName,substrate
"HumanObservation","62635","","Fungimap Recorder Number: 1287","host: Allocausurina","2009-07-09","9/7/2009","Wet sclerophyll forest","QLD","Linda Garrett Park, Mapleton","Linda Garrett Park, Mapleton","-26.608333333333334","152.83555555555557","EPSG:4326","-26.608333333333334","152.83555555555557","EPSG:4326","1000","Cyptotrama aspratum","trunk"

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-hubs#116
