### ISSUE TITLE
Not connecting to cassandra

### ISSUE THREAD

**Issue by DuncanRowland** [AtlasOfLivingAustralia/biocache-store#190]
Installed via ala-demo I have cassandra running and can connect via cassandra-cli (the log shows "Handshaking version with localhost/127.0.0.1:9160"). And "nodetool status" says Up and Normal.
But I can't seem to get the biocache tool to connect in the same way. I've tried all the likely alternatives in biocache-config.properties I can think of (localhost, 127.0.0.1,static ips, ports, etc.), but it never connects to cassandra. My firewall settings look OK (I've opened all ports for testing, running Ubuntu 14.04 on Google's CE). Any suggestions on what I can try next?
Many thanks, -Duncan.

**Comment by djtfmartin** [comment]
closing - the new demo is using cassandra 3
