### ISSUE TITLE
Method to change unique key data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-store#20]
ability for a data set to change the values in their unqiue fields without having to completely delete and reload the data: e.g. when an institutionCode is changed.

ability to provide the ALA record identifier with the new data set so that the records are updated rather than deleted

Will this also allow the key fields to be reset e.g. instead of using eventID and scientificName the data set now uses catalogNumber

**Comment by djtfmartin** [comment]
This is possible in the 2.x branch now, by exporting the occ_uuid data, manipulating it and writing back.
