### ISSUE TITLE
Taxon not matched when accent character present in scientific name

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#203]
Some SAM records are only being matched to `genus` despite the records providing a valid `scientificName` as well valid `genus` and `specificEpithet` fields. E.g. this record is correctly matched:

http://biocache.ala.org.au/occurrences/97ceb83a-b2a2-4cb9-914b-369d76eac47d

but this one is not:

http://biocache.ala.org.au/occurrences/6f15ef99-9f1c-47fa-aeed-fb311780b490

The 1st record was provided with `genus` and `specificEpithet` but no `scientificName`. The second record was provided with all 3 but the `scientificName` field contains an unrecognised character:

Litoria ewingii (Dum�ril & Bibron, 1841)​

Fix is to be tolerant of the non-UTF-8 char (ignore it maybe) and to check for `genus` and `specificEpithet` in order to confirm the match.

**Comment by nickdos** [comment]
Comments from Bob Mesibov:

>Hi, Nick.
>
>That's the replacement character (hex EF BF BD) and derives either from failure to convert the SAM upload to UTF-8 or (less likely) incorrect conversion. Please see my Data Cleaner's Cookbook: https://www.polydesmida.info/cookbook/encoding2.html
>
>SAM is particularly awful in its data management and is responsible for a large number of the structural errors I find in ALA. SAM data featured in a talk I gave in Melbourne late last year (abstract below), as did ALA.
>
>ALA came under fire in the Q and A after the talk because some of its procedures (like name matching) result in altered records, while ALA policy is not to change any uploaded data. The solution I recommended was for data fixes to happen before the data get to ALA.
>
>You'll notice in my signature that I now do this commercially (https://www.datafix.com.au). Business with biodiversity data is lousy because the data providers think they're doing a great job, and ALA and other aggregators prefer to do it the hard way, with filters and flaggers at the receiving end.
>
> Cheers,
Bob

**Comment by djtfmartin** [comment]
looks to be fixed
