### ISSUE TITLE
Checkpointing for large operations

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#209]
It would be helpful to have checkpointing for bulk processing and bulk indexing operations, so that if the job falls over halfway through, it can start from a last known good point, rather than from the beginning. That way, if a 4-day job falls over in the last hour, it can be restarted easily.

**Comment by djtfmartin** [comment]
Ive added this for cassandra 3. Just a single file based checkpoint thing which uses the index token ranges. Works well for processing and indexing.

**Comment by djtfmartin** [comment]
this is done for version 2.x and i dont think we'll do for 1.9.
