### ISSUE TITLE
biocache processing doesn't process provided values properly

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-store#217]
when a correct higher taxon value is correctly provided in the source data e.g. class "Insecta" the processing code doesn't populate the class.p value and so it's not indexed - causes a set of records in the index without a value in the class index facet. e.g. http://biocache.ala.org.au/occurrence/search?q=-class%3A* even though they have a value in cassandra.

**Comment by djtfmartin** [comment]
I think this is fixed, at least i cant find records where this is the case now.
