### ISSUE TITLE
Load check for empty files 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#25]
Add an extra step that checks for empty files before attempting to load a data resource.

Particularly important for ANWC because they automatically generate and upload archives that fail. These ZIP files will contain empty CSV files.

**Comment by adam-collins** [comment]
There was an empty csv check in DwcCSVLoader missing from AutoDwcCSVLoader. 

Is there a recent example or log error to confirm this was the issue?
