### ISSUE TITLE
Unused cassandra fields

### ISSUE THREAD

**Issue by reupost** [AtlasOfLivingAustralia/biocache-store#260]
It seems there are some DwC fields in Cassandra, e.g. organismquantity, organismquantitytype and maybe 50 others, that are not included in the model properties. As such, any dataset with these fields will have the data loaded into the Cassandra miscproperties field instead of the appropriate field.

Is this intentional, or am I misunderstanding the code? I've tested locally by adding the missing properties and the data is then correctly loaded into the appropriate Cassandra field.

**Comment by djtfmartin** [comment]
sounds like a bug. we should add those fields to the model classes

**Comment by nickdos** [comment]
I can now see records in the index with `organism_quantity` and the `index/fields` JSON file indicates these fields are part of DwC. I also tested a download with DwC fields selected and the `organismquantity` was there.
