### ISSUE TITLE
Add visible warnings when unexpected non-comment lines are found in indexFields.txt

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#262]
The current code is silently ignoring non-comment lines in ``indexFields.txt`` if they don't contain exactly 7 columns. This check should have visible warnings to avoid latter errors from issues that could have been identified early when ``indexFields.txt`` is parsed:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/0398df452abd311a0463c6d4a4b4e8449bc93f6d/src/main/scala/au/org/ala/biocache/index/IndexDAO.scala#L1728

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
