### ISSUE TITLE
Make enum out of the magic numbers used in indexFields.txt

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#263]
The magic numbers used in indexFields.txt are incomprehensible in code because they are not enumerated. This results in the following code for knowing whether to include a field in the index or not:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/0398df452abd311a0463c6d4a4b4e8449bc93f6d/src/main/scala/au/org/ala/biocache/index/IndexDAO.scala#L1405-L1438

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
