### ISSUE TITLE
Offer all available fields in Darwin Core Archives created by DwCACreator

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#276]
The field list offered in Darwin Core Archives created by DwCACreator is statically created and does not contain all Darwin Core Terms or any non-Darwin Core Terms and is leaving out information in files that are sent to GBIF and are being represented as "complete" by ALA.

The field list should be dynamically generated based on the requirements of each data resource.

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/96a67f80f460d0a7ecd4ee3da5550b3bfffa4d3e/src/main/scala/au/org/ala/biocache/export/DwCACreator.scala#L275

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
