### ISSUE TITLE
delete records job need to accept AND or an fq

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-store#285]
more complex delete jobs need additional parameters AND or fq usually for a data set and date range

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr2287&fq=-last_load_date%3A[2018-01-05T01%3A33%3A51Z+TO+*]

**Comment by sadeghim** [comment]
Assigned it to @M-Nicholls to confirm it works correctly.

**Comment by M-Nicholls** [comment]
confirmed
