### ISSUE TITLE
MinMax Elevation/Depth processing issue

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-store#297]
Location processing for following fields has a bug that when one of the Min and Max fields is not present, the result will be null for both. While there can be situations that only one is provided:
```
minimumElevationInMeters, 
maximumElevationInMeters, 
minimumDepthInMeters, 
maximumDepthInMeters
```

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
