### ISSUE TITLE
Occurrence records with invalid layer sampling?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#30]
_From @Tasilee on August 19, 2014 13:9_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=659
*date:* Thu May  1 22:17:26 2014
*author:* leebel...@gmail.com
 ---

Summaries of occurrence queries from Kristen Williams are suggesting (serious?) anomalies in the sampling of spatial layers of some records during processing. For example, if a query is constructed on 

Country = n/a AND
IBRA = n/a AND
IMCRA = n/a AND
el884 (bathymetry and elevation) = n/a

it should only return records that occur outside Australia. The following query however

[http://biocache.ala.org.au/occurrences/search?fq=-ibra%3A*&fq=-imcra%3A*&fq=-country%3A*&fq=-el848%3A*&wkt=POLYGON((96.6%20-58.0,159.8%20-58.0,159.8%20-10.5,96.6%20-10.5,96.6%20-58.0))#tab_mapView](http://biocache.ala.org.au/occurrences/search?fq=-ibra%3A*&fq=-imcra%3A*&fq=-country%3A*&fq=-el848%3A*&wkt=POLYGON((96.6%20-58.0,159.8%20-58.0,159.8%20-10.5,96.6%20-10.5,96.6%20-58.0))#tab_mapView) 

produces 40,954 records, most of which ARE in 'Australia' and are terrestrial. 

A few records are marine (correctly or not as I haven't checked yet) but should still be on the bathy/topo layer (and IMCRA). 

There are also a few on offshore islands, which should also be on the bathy/topo layer, if not IMBRA or IMCRA - and they should also be 'Australia' but that may be another issue. 

The WKT (bounding box) here just includes Australia and associated islands. 

PS: Diagnosis of classification of the records would be made easier if `#658` were solved.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#78_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 13:9_


*date:* Mon May  5 23:02:29 2014
*author:* moyesyside
 ---

Miles any thoughts on this ? Looks like sampling hasnt been ran or there are some problems with certain datasets.

 ---
**UPDATES:**
*Cc:* milo_nic...@hotmail.com
*Status:* Accepted

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 13:9_


*date:* Mon May  5 23:25:48 2014
*author:* milo_nic...@hotmail.com
 ---

looks like it's just subsets of records that haven't sampled properly - I re-sampled the climatewatch records and they dropped out of the query.  I'll sample/process/index the others and see if there's anything left.

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 13:9_


*date:* Mon May  5 23:45:59 2014
*author:* milo_nic...@hotmail.com
 ---

I've sorted out the records that can be easily re-sampled, unless this is urgent I'd prefer to wait for updates to the remaining large data sets - it doesn't seem worth reprocessing an entire states data set for a few hundred records?

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 13:9_


*date:* Mon May  5 23:50:46 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Cc:* -milo_nic...@hotmail.com
*Owner:* milo_nic...@hotmail.com

**Comment by nickdos** [comment]
_From @Tasilee on August 19, 2014 13:9_


*date:* Tue May  6 00:04:47 2014
*author:* leebel...@gmail.com
 ---

Great that this is acknowledged and will be addressed. I do think it may be more than a few hundred records though. I would think it is well into the thousands?

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 13:9_


*date:* Thu May 29 22:46:18 2014
*author:* moyesyside
 ---

full resample and re-index done. this now affects 4 records as opposed to 40k. Downgrading but keeping open for those 4.

 ---
**UPDATES:**
*Labels:* -Priority-High Priority-Medium
*Status:* Started

**Comment by djtfmartin** [comment]
closing. this is very old and no longer relevant as these indexes dont exist
