### ISSUE TITLE
Documentation required for loading media files from Darwin Core Archives

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#301]
It is currently difficult to analyse the code related to loading media files from inside of Darwin Core Archives (not using web URLs). This is currently blocking loading sounds for ANWC, but the documentation should also show how to loading images direct from Darwin Core Archives that have not been hosted on websites.

**Comment by ansell** [comment]
My current impression from reading the newly changed source code is that the documentation for this will be

1. The `core` **must** have its `rowType` as:

```
http://rs.tdwg.org/dwc/terms/Occurrence
```

2. The `extension` containing the media links **must** have its `rowType` as *either*:

```
http://rs.gbif.org/terms/1.0/Image
```

or, preferably, 

```
http://rs.gbif.org/terms/1.0/Multimedia
```

3. The `extension` media links **must** be in a column named `identifier`

**Comment by nickdos** [comment]
Moved to waiting for while PA on leave

**Comment by ansell** [comment]
Will document the requirements for loading media files from Darwin Core Archives in confluence when this get back to the top of my list.

**Comment by ansell** [comment]
Documentation created in Confluence at:

https://confluence.csiro.au/display/ALASD/Loading+images+from+Darwin+Core+Archives

**Comment by charvolant** [comment]
I've read this over and it's correct
