### ISSUE TITLE
verbatimSRS overrides geodeticDatum when both are set

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#304]
There was a bug introduced in the logic of the following commit that causes verbatimSRS to override geodeticDatum, and incorrectly matches verbatimSRS against decimalLatitude/decimalLongitude, to incorrectly reproject them.

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/ff10f6f8021b5a1f6227185e8b0feb6fa826aa6a#diff-37f4d4cb38beb1048b4c272a9a890247R418

There is currently no test to verify the case where both verbatimSRS (and verbatim coordinates) and geodeticDatum (and non-verbatim coordinates) exist, and hence the bug was not picked up when the commit was made.

**Comment by djtfmartin** [comment]
Fixed in a release 2.4.1. Not yet deployed into production.
