### ISSUE TITLE
DwC eventDate supplied as a range is not correctly handled in processed value

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#31]
E.g. [http://biocache.ala.org.au/occurrences/7adfb98f-264b-45b2-bcee-fd9d811c59d8](http://biocache.ala.org.au/occurrences/7adfb98f-264b-45b2-bcee-fd9d811c59d8)

Event date  1770-04-29/1997-12-31   1770-04-29

Fix might be to create an option field for the upper range value? 

(interim fix) Better default handling could be to use the upper range as preferred value as well?

**Comment by charvolant** [comment]
I've just run afoul of this when loading records from some survey data. Any chance of bumping the priority up a bit?

**Comment by adam-collins** [comment]
Adding processed.event.eventDateEnd when it is different from eventDate.

**Comment by adam-collins** [comment]
Did not notice biocache-service issue. Need to index as well.

**Comment by nickdos** [comment]
Just noticed that SOLR supports date ranges for indexing as well - see docs:

https://cwiki.apache.org/confluence/display/solr/Working+with+Dates#WorkingwithDates-DateRangeFormatting

**Comment by charvolant** [comment]
Will that handle an overlapping ranges of dates? Eg. supplied date in DwC form is 2010-04/05 and query is 2010-05-21 TO 2010-06-21

**Comment by adam-collins** [comment]
Need to merge solr5 branch to make DateRangeField available for use. This would make queries more simple than what works now https://github.com/AtlasOfLivingAustralia/biocache-service/issues/44

biocache-store also needs extend DwC date parsing to correctly set start and end dates of ranges.
