### ISSUE TITLE
Add no media store for sandbox

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#318]
The sandbox might be better off not storing thousands of images in a local store. The current options available are a local media store or a remote media store but no null-op media store.

See also https://github.com/AtlasOfLivingAustralia/biocache-store/issues/316

**Comment by ansell** [comment]
Confirmed: https://github.com/AtlasOfLivingAustralia/biocache-store/blob/da151fc525bd24b0bc50cd70926b131e5906ce3c/src/main/scala/au/org/ala/biocache/Config.scala#L47-L58

Sorry, I misunderstood earlier what would happen when the remote media URL was not specified, it doesn't seem to currently have a configuration setting to skip all media loading.

**Comment by charvolant** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/biocache-store/pull/319
