### ISSUE TITLE
Incorrect taxon matching for SAM records (ignoring higher taxa hint from collectory)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#32]
_From @nickdos on August 19, 2014 13:26_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=722
*date:* Sun Jun 29 17:55:32 2014
*author:* nickdos
 ---

Alexis identified some records being matched to non-animal higher taxa despite the collectory specifying animalia as the higher taxon hint for this collection.

[http://biocache.ala.org.au/occurrences/5bcd1ec2-211c-4bf6-9993-414d9e815898](http://biocache.ala.org.au/occurrences/5bcd1ec2-211c-4bf6-9993-414d9e815898)

and 

[http://biocache.ala.org.au/occurrences/d6fb923e-6c2c-4937-8e2a-08b9187e252b](http://biocache.ala.org.au/occurrences/d6fb923e-6c2c-4937-8e2a-08b9187e252b)
[http://biocache.ala.org.au/occurrences/100c8df7-de72-432c-90ce-9dbe4bf5113d](http://biocache.ala.org.au/occurrences/100c8df7-de72-432c-90ce-9dbe4bf5113d)
[http://biocache.ala.org.au/occurrences/ed6cb62d-3f8d-4cd9-900e-a8d5d7e13abd](http://biocache.ala.org.au/occurrences/ed6cb62d-3f8d-4cd9-900e-a8d5d7e13abd)

which appear to be matching to genus via a fuzzy match despite having a family specified which appears to have been ignored.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#85_

**Comment by nickdos** [comment]
*date:* Sun Jun 29 18:28:03 2014
*author:* nickdos
 ---

Looking at the collection page: [http://collections.ala.org.au/collection/show/125](http://collections.ala.org.au/collection/show/125)

I see that the "taxonomic range" has animalia but the "taxonomic hint" section only includes:

class = reptilia
class = amphibia

Does "kingdom = animalia" need to be included here for the names matching perhaps?

**Comment by M-Nicholls** [comment]
I saw that the taxonomic hint was updated to kingdom=animalia and reprocessed the dataset but the matching is still incorrect.

It looks like the actual species doesn't exist in the NSL so we don't have a name to match it to, there's not entry for the genus but there is for the family: Hylidae

The records should be matched to the the family rather than the fuzzy match to a different kingdom

**Comment by djtfmartin** [comment]
The records listed above have been removed so its no longer possible to look into whats happening here. closing
