### ISSUE TITLE
Calls to collectory data resource should use a different path for temporary data resources

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#321]
See, eg, https://github.com/AtlasOfLivingAustralia/biocache-store/blob/f5e7c6b00dae7ff5a9021e3e3267e3c30db3d5e2/src/main/scala/au/org/ala/biocache/caches/AttributionDAO.scala#L89 which should call /tempDataResource/ rather than /dataResource/

Is there any way, other than looking at the data resource uid, of knowing whether it's a temporary resource or not?

**Comment by ansell** [comment]
The only way I know of it checking for `drt` at the start of the uid.

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
