### ISSUE TITLE
Multiple records sharing same uuid

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-store#33]
In Cassandra there are records having same uuid. For example rowKeys: 
dr376|CANB|CANB353096 
dr376|CANB|CANB353096.1
have same uuid and some fields have different values (specifically **deleted_** is TRUE for the first one).

**Comment by djtfmartin** [comment]
Do we have any idea how to reproduce this ?

**Comment by djtfmartin** [comment]
This is the result of a one off load for this data resource using this class:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/test/scala/au/org/ala/retrofit/CANBDwCALoader.scala

I suspect we just need to delete one of the variants. Im going to transfer this to the data management issues and assign to @sadeghim

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/data-management#117
