### ISSUE TITLE
outlier layer count off by 1

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-store#331]
The reverse jacknife processing is setting the outlier for layer count by 1 too few e.g. outlier for 5 layers is showing as outlier for 4 layers: https://biocache.ala.org.au/occurrences/search?q=outlier_layer_count%3A*&fq=outlier_layer_count%3A%224%22 check record details and the record will show 5 layers in the outlier section.

related to support ticket : https://support.ehelp.edu.au/a/tickets/30657

**Comment by djtfmartin** [comment]
The record is now showing 4 layers so i believe this is fixed.

**Comment by nickdos** [comment]
Tested ✅ good for CAB.
