### ISSUE TITLE
Upgrade to sds-1.4.5

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#334]
Biocache-store is using sds-1.4.4. This is incompatible with recent changes to the name index, and an upgrade to sds-1.4.5 is required. A switch to the new SDS server was blocked by biocache-store breaking afterwards, although the exact stacktrace is lost to the universe due to a low rentention period on the logging for the jenkins job that showed the error.

- [x] Upgrade dependency to sds-1.4.5
- [x] Test with new (current for everything except SDS) nameindex and` aws-sds-2019.ala.org.au`

**Comment by ansell** [comment]
@charvolant This issue hasn't been moving across the board, but the `develop` branch is using the `sds-1.4.5` library at this point so it seems like it fits in the QA column. Can you confirm the QA status for it and move it along when QA is done?

**Comment by ansell** [comment]
Still need to test this against the new SDS server, moving back to QA to make sure that test occurs and then we can switch SDS servers.

**Comment by nickdos** [comment]
Plan is to deploy new SDS test server with Ubuntu 20 and point sandbox test at that.
