### ISSUE TITLE
Remove establishmentMeans processor

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#339]
The processor for `establishmentMeans` is no longer needed by AVH as they have moved from HISPID to Darwin Core.

- [ ] Remove `MiscellaneousProcessor.processEstablishmentMeans` https://github.com/AtlasOfLivingAustralia/biocache-store/blob/0398df452abd311a0463c6d4a4b4e8449bc93f6d/src/main/scala/au/org/ala/biocache/processor/MiscellaneousProcessor.scala#L93-L118

Refs https://github.com/AtlasOfLivingAustralia/data-management/issues/504#issuecomment-525538145

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
