### ISSUE TITLE
Issue or limit with the collectionCodes ?

### ISSUE THREAD

**Issue by santiagomrv** [AtlasOfLivingAustralia/biocache-store#346]
Hi team,
I'm not sure if this is an issue or a specific limit. The question in that we are trying to ingest 2 datasets with 20  and 40 collectionCodes, and the problem is that the collection doesn't have all occurrences connected. So we suppose that maybe it is some kind of limit on the process step of biocache-store or a bug.

**Comment by djtfmartin** [comment]
thanks @santiagomrv  - Im not aware of any limit on the number of collection codes that can be in use, and 20-40 doesn't sound too high to me. Perhaps something else is causing the issue.

**Comment by brucehyslop** [comment]
biocache-store has been replaced by pipelines.
