### ISSUE TITLE
Support the export of index fields into CSV

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#35]
As discussed. By default dont include sensitive coordinates, but support a  flag to allow for it.

**Comment by adam-collins** [comment]
Export of index fields to a CSV during indexing is supported. One CSV is produce for each indexing thread.

Set the property export.index.as.csv.path to enable the export of all non-sensitive fields in the CSV. 

Set the property export.index.as.csv.path.sensitive to enable the export of all fields in the CSV.

**Comment by adam-collins** [comment]
Requires testing.
