### ISSUE TITLE
Export-stream include column headers

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#36]

**Comment by adam-collins** [comment]
export-stream now includes column headers

**Comment by djtfmartin** [comment]
FYI @M-Nicholls  - relevant for exports for states

**Comment by adam-collins** [comment]
Requires testing.

**Comment by M-Nicholls** [comment]
looking good so far, I'll run a few more and re-open if I come across any problems.
