### ISSUE TITLE
Records with swapped latitude/longitude don't have them corrected.

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#384]
The code at https://github.com/AtlasOfLivingAustralia/biocache-store/blob/dda875fa44eebadeaf5c9c380778cf3ac8ca2ae3/src/main/scala/au/org/ala/biocache/processor/LocationProcessor.scala#L783-L793 suggests that the lat/long will be swapped back if obviously swapped. However, this doesn't seem to happen.

Instead, a swapped coordinates flag is included but no coordinates out of range flag.
[test-lat-long.csv.zip](https://github.com/AtlasOfLivingAustralia/biocache-store/files/4686509/test-lat-long.csv.zip)

**Comment by peggynewman** [comment]
Closed as migrated to pipelines.
