### ISSUE TITLE
DWCACreator not handling double quotes

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-store#42]
Current version using opencsv writer which isnt escaping double quotes properly.

**Comment by sadeghim** [comment]
There are two records in dr340 which causes this problem as they are not ingested correctly into ALA:

http://biocache.ala.org.au/occurrences/bf8bb82c-1a3d-4d65-ac2c-e7ed35df4f9f
http://biocache.ala.org.au/occurrences/dd1d144e-3e24-4f27-9a0d-10324066860b

After removing these two from the archive, I was able to load it into IPT and publish it successfully.

**Comment by djtfmartin** [comment]
should we delete these records ?

**Comment by sadeghim** [comment]
Deleted them from the Cassandra DB. This should solve the problem.Will see the result after reindex.

**Comment by djtfmartin** [comment]
is this resolved ? shall we close this issue ?

**Comment by sadeghim** [comment]
I tested the latest export and It went without any issue. So, I am closing this issue.

**Comment by djtfmartin** [comment]
cheers @sadeghim
