### ISSUE TITLE
Use of common names for Orders

### ISSUE THREAD

**Issue by SaulCunningham** [AtlasOfLivingAustralia/biocache-store#44]
I was recently searching for specimens by location.
Having established there were a few hundred records in the locality of interest, I then wanted to see if any were bees. On the left side of the screen I was offered choices I could click to narrow the selection by taxonomy. For a while I assumed there were no bees in the selection. It took me quite a while to realise the choices were meant to represent insect orders, and therefore to see the bees I should have selected "ants", which was the common language word chosen to describe hymenoptera.

I do not think any users who rely on common names will understand that by this taxonomy, ants are in fact bees. The common name for the family should at least be "wasps, ants, bees"

**Comment by djtfmartin** [comment]
This has been done. We should get these same subgroups visible in the Explore Your Area tool.

<img width="1370" alt="screenshot 2015-07-14 12 25 08" src="https://cloud.githubusercontent.com/assets/444897/8672152/8abf42f8-2a23-11e5-99e2-aa71c6a74aa2.png">

cc @nickdos
