### ISSUE TITLE
Load DwCA with multiple images

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-store#48]
From data management, see https://github.com/AtlasOfLivingAustralia/data-management/issues/66 for details. DwCA can contain images. These should be loaded along with the occurrence data.

**Comment by djtfmartin** [comment]
this has no been implemented in

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/fad237d14b2c17177475e4116f12b7e5567fb8cb
