### ISSUE TITLE
Improve basis of record vocabulary for GBIF import

### ISSUE THREAD

**Issue by timrobertson100** [AtlasOfLivingAustralia/biocache-store#51]
When using the import from GBIF, the basis of record is not interpreted as GBIF use things like MACHINE_OBSERVATION which is not understood.

The GBIF basisOfRecord is driven by this enumeration:
https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/BasisOfRecord.java

**Comment by cgendreau** [comment]
Just an idea, BasisOfRecordParser
https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/BasisOfRecordParser.java

**Comment by djtfmartin** [comment]
Fixed in https://github.com/AtlasOfLivingAustralia/biocache-store/commit/062068f89f7ac902042502f6a006486eabedd5b7

Integrating the GBIF parser makes a lot of sense, but its for another day.
