### ISSUE TITLE
Resource cleanup command doesn't take --test option into account

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-store#52]
The command:

    biocache resource-cleanup  --test --delcols -c decimalLatitude,decimalLatitude.p,decimalLongitude,decimalLongitude.p dr728 columns

did commit the changes to Cassandra while it should simulate the cleanup without removing anything (according the cmd usage).

**Comment by sadeghim** [comment]
It also doesn't care about the load date! This command:

    biocache resource-cleanup -d 2015-05-15 --delcols -c decimalLatitude,decimalLongitude --test dr346 columns

removed these two columns from all records even those loaded before 15th May.

**Comment by adam-collins** [comment]
-d and --test added for the examples in the issue and elsewhere in resource-cleanup where found missing.
