### ISSUE TITLE
Export-stream missing a tab separator when the -qa option is used

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-store#55]
When using the -qa option to include the quality assertions in the export there isn't a separating tab in between the last column of the field list and the first column of the QA fields.  These get combined into a single header – the columns don’t match the data after that.
 
e.g. sensitive_localityidentificationIncorrect which should be sensitive_locality[tab]identificationIncorrect

**Comment by M-Nicholls** [comment]
still looks to be happening - tested using the Jenkins job - http://ala-mccartney.it.csiro.au/job/Test%20export%20Job/

**Comment by djtfmartin** [comment]
fixed ?
