### ISSUE TITLE
Thumbnails not created for images with a URL that contains a ?

### ISSUE THREAD

**Issue by jholetschek** [AtlasOfLivingAustralia/biocache-store#72]
If the URL for an image contains "?", the URL is cropped at the question mark. The file is cached, but no thumbnails are created, so no images are viewed on the occurrence details page or the "Record images" tab.

Example URL:
http://mediastorage.bgbm.org/fsi/server?type=image&source=specimentool%2FAnimals%2FBirds%2FDromaius_novaehollandiae_2008-10-27_gd_AU2_381.JPG

**Comment by adam-collins** [comment]
Images still need an extension. In the above example it appears at the end, after ?, so it will work.

Tested with sandbox instance and media.store.local=true.

**Comment by jholetschek** [comment]
I've attached a screenshot for the image URL mentioned above. Note the missing thumbnail and the URL of the link "view original file" on the bottom. Clicking the link will open the file, which is stored at file system path biocache-media/dr6/13133/1f553d5b-da2f-4bf0-b2c0-afd1c2f72996/server.

We're using the biocache version with gitCommitID=e80bea85792554bc71a3db620a6d04021163044c

![ala](https://cloud.githubusercontent.com/assets/11058397/9680500/99ce5e6c-52f7-11e5-9114-ce05f90046f6.jpg)

**Comment by adam-collins** [comment]
The update is still on a branch, https://github.com/AtlasOfLivingAustralia/biocache-store/tree/sprint3-1

When testing there may be a need to alter file permissions of biocache-media.

**Comment by jholetschek** [comment]
Permissions are like this
drwxrwxr-x  6 tomcat7   tomcat7   4.0K Aug 13 16:15 biocache-media

Since this affects only records with the given URL patterns, permissions shouldn't be the issue.

**Comment by adam-collins** [comment]
For testing, this branch can be compiled and replace the current biocache-store jar in biocache-service. An alternative, using your compiled jar and importing a record with load-local-csv.

For the problem URL, the link on the image itself is of the form http://sandbox.vagrant1.ala.org.au/biocache-media/drt1/19961/aca0bc56-15c1-44c0-9705-80dc62f59597/server__large and there is a file created with the same name.

**Comment by jholetschek** [comment]
Where in the Ansible scripts/configs do I have to put the URL https://github.com/AtlasOfLivingAustralia/biocache-store/tree/sprint3-1 to update my installation to this branch?

**Comment by jholetschek** [comment]
I now tested the changes. The thumbnails are created correctly now, great! Apart from the image there are now three additional files stored: __large, __small and _thumb.

But the URL in the HTML page is malformed, "__large" is appended to the domain, not the file name:
href="http://bgbm-ala-demo.bgbm.fu-berlin__large.de/biocache-media/dr6/27395/b1d8e2ab-7892-4037-8644-861f8b03319e/server"
img src="http://bgbm-ala-demo.bgbm.fu-berlin__small.de/biocache-media/dr6/27395/b1d8e2ab-7892-4037-8644-861f8b03319e/server" style="max-width: 100%;"

The correct URL would be 
http://bgbm-ala-demo.bgbm.fu-berlin.de/biocache-media/dr6/27395/b1d8e2ab-7892-4037-8644-861f8b03319e/server__large

**Comment by adam-collins** [comment]
Not ready for testing yet with ansible scripts. A biocache-service update to use this new biocacache-store version is also required.
