### ISSUE TITLE
Habitat and mixing Occurrence and Profile data

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#73]
_From @nielsklazenga on July 24, 2015 2:35_

The use of the word "habitat" to indicate whether something is marine or not has always been a thorn in the eye, but that was just a label and you didn't have to display the filter if you didn't want to see it. Some time ago, however, I noticed that on the Occurrence detail pages 'Habitat' for the far majority of AVH records is given as 'Terrestrial', with the actual habitat information, if provided, given after 'Supplied as", which is pretty unacceptable data tampering.

The marine/non-marine distinction is not 'habitat' and 'terrestrial' may mean 'occurring on land' when it is set off against 'marine', but in the context of habitat it means something completely different, namely 'growing on the ground' – and not in a tree or on a rock etc. Ornithologists should be up in arms about this, if they have been paying attention.

The bigger issue here is that Profile data is presented as processed Occurrence data. Profile data is based on Occurrence data and therefore replacing the provided Occurrence data with Profile data is circular, unscientific and misleading.

I suspect that if I do a spatial analysis, I'll find that things marine will generally occur in the sea, but there will be other Profile data that is more useful to have in the Biocache. When that is done, the Profile information should be clearly separated from the Occurrence data, just like the political boundaries and environmental data is now (and even that could be done a bit more clearly).

I am only assuming the 'Terrestrial' comes from the same source as the 'Species habitats' filter, as I don't know where else it could come from. The 'Non-marine' in that filter, however, is way preferable over 'Terrestrial', but I guess sounds less habitatty, so why not remove it from the Occurrence detail page altogether and move the provided habitat information up to where the other provided information is?

When putting Profile data into the Biocache, as far as I can see, [`dwc:habitat`](http://rs.tdwg.org/dwc/terms/habitat) is the only term for which there will be a conflict between Profile and Occurrence data. There should be separate "fields" in the BioCache for both uses. However, in a Profile, `habitat` should be used for terms from the [IUCN Habitat Vocabulary](http://rs.gbif.org/vocabulary/iucn/habitat.xml), or, preferably, from a more fine-grained, possibly Australian, vocabulary that doesn't exist yet. For the stuff that is currently in `species_habitats`, the terms [`isMarine`](http://rs.gbif.org/terms/1.0/isMarine), [`isTerrestrial`](http://rs.gbif.org/terms/1.0/isTerrestrial) and [`isFreshwater`](http://rs.gbif.org/terms/1.0/isFreshwater) should be used.
. 

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#136_

**Comment by nickdos** [comment]
This is a data processing issue so will move it to biocache-store.

**Comment by adam-collins** [comment]
1) species_habitats is from occ taxon.habitats built by BIE. BIE comments describe Non-marine as translating to isTerrestrial OR isFreshwater, so those new terms are not compatible. Other than renaming species_habitats, and I do not think it should be, I am not sure what to do with this one.

2) processed.location.habitat contains layer sampling determined value of Marine or Terrestrial. raw.location.habitat contains the data set supplied value habitat, dwc:habitat. I am wondering processed.location.habitat should contains the same as raw.location.habitat, and the layer sampling determined value be renamed to something else, e.g. process.location.domain.

**Comment by djtfmartin** [comment]
The marine/terrestrial stuff is all driven by the data from IRMNG which is loaded into the biocache taxon tables with this class:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/load/TaxonProfileLoader.scala#L28

The aim behind this was purely to flag records for sharks in the middle of Australia as being suspect.

If adding the marine/terrestrial property to the record is a bad thing then we can just stop doing it and keep the check. Adding the property to the record was really only done so there was some traceability in the system.

**Comment by adam-collins** [comment]
Confused now. 

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/load/TaxonProfileLoader.scala#L77 only writes "Marine" or "Terrestrial" to taxon table. I'm not sure if there is a "Terrestrial" habitat value in the taxon table. Maybe this needs an update.

https://github.com/AtlasOfLivingAustralia/bie-profile/blob/master/src/main/java/org/ala/model/Habitat.java#L26 lists the habitats in the taxon table; "Limnetic", "Marine", "Non-marine", "Marine" and "Non-marine". No idea how they end up being used.

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/views/occurrence/_recordCore.gsp#L704, if not removing it, processed.location.habitat should be displayed together with speciesHabitat when the assertion is set.  raw.location.habitat is unrelated.

**Comment by djtfmartin** [comment]
I'd ignore the BIE stuff, its old and it not longer is used on the biocache side.

**Comment by nielsklazenga** [comment]
Adding the marine/terrestrial property to the Occurrence record is not a bad thing, but we need another term for it than `habitat` and it should be clear that it is not an interpretation of the habitat information provided with the record (cf. Adam's last remark). I can't think of a good term, but I'll ask around. Probably best not to make hasty changes. Thanks for looking into it.

For what it's worth, I think that what we (in AVH) deliver as `habitat` would be better delivered as `locationRemarks`, so that `habitat` can be an interpreted field with a controlled vocabulary, like the IUCN Habitat vocabulary.

**Comment by nielsklazenga** [comment]
The most fitting term I can think of at the moment is 'biome'. There are a 'marine biome' and a 'freshwater biome'. The terrestrial biomes are normally split up into 'desert', 'tundra', 'grassland' and 'forest' biomes, but lumping these together at worst makes a rather crude classification and does not change the semantics of the term.

**Comment by AaronWilton** [comment]
I agree with Niels - biome seems to be an appropriate term.

**Comment by nickdos** [comment]
I have a feeling this marine, non-marine data comes from IRMNG - http://www.cmar.csiro.au/datacentre/irmng/

**Comment by nielsklazenga** [comment]
Yes, that's what Dave said and what is in the AVH Help page, http://avh.chah.org.au/index.php/help/data/#Ecoregion. I can't remember where we got 'ecoregion' from.

**Comment by nielsklazenga** [comment]
Just a thought, any reason why we can't just call this IRMNG?

**Comment by djtfmartin** [comment]
Im not sure. IRMNG contains quite a bit of information, not just this flag.

**Comment by adam-collins** [comment]
Fields are now:
- classification.speciesHabitat is from IRMNG. I found IRMNG referring to this as habitat. It is from the occurrence taxon name match. No change.
- location.biome is from marine and terrestrial layers together with the occurrence location. Changed the name from processed location.habitat
- location.habitat is from the imported occurrence. Changed to put this value into the processed location habitat. It was previously only in raw location habitat.

The habitatMismatch assertion is a comparison of taxon and location, that is now classification.speciesHabitat and location.biome. No change.

Labels on the hubs page, e.g. ecoregion, are not addressed here.

**Comment by nielsklazenga** [comment]
Thanks Adam, Dave, that looks fine to me.

**Comment by adam-collins** [comment]
more than 'isMarine' is available in the updated file http://www.irmng.org/export/

**Comment by djtfmartin** [comment]
closing. this is done
