### ISSUE TITLE
Use a cached fieldsdb source for high frequency fieldsToSample requests

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-store#74]
This line does call layers-service/ws/fieldsdb too many times.

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/746040cc7f16eca082b4ac9551e3109366e303e5/src/main/scala/au/org/ala/biocache/caches/LocationDAO.scala#L133

**Comment by djtfmartin** [comment]
changing to from a def to

```
  lazy val fieldsToSample
```

will fix this

**Comment by adam-collins** [comment]
fieldsToSample should update for sandbox sampling but it is not necessary for the cli. Adding a var for caching and extending the function to
```
def fieldsToSample(refresh:Boolean = true) = {
```
